from __future__ import annotations

from datetime import datetime
from typing import Any, Protocol


class CanaryRepository(Protocol):
    def create_application(self, application: dict[str, Any]) -> dict[str, Any]: ...

    def get_application(self, app_id: str) -> dict[str, Any] | None: ...

    def get_application_by_name(self, app_name: str) -> dict[str, Any] | None: ...

    def list_applications(self, filters: dict[str, Any]) -> list[dict[str, Any]]: ...

    def update_application(self, app_id: str, updates: dict[str, Any]) -> dict[str, Any]: ...

    def create_version(self, version: dict[str, Any]) -> dict[str, Any]: ...

    def get_version(self, version_id: str) -> dict[str, Any] | None: ...

    def list_versions(self, app_id: str, filters: dict[str, Any]) -> list[dict[str, Any]]: ...

    def update_version(self, version_id: str, updates: dict[str, Any]) -> dict[str, Any]: ...

    def create_experiment(self, experiment: dict[str, Any]) -> dict[str, Any]: ...

    def get_experiment(self, experiment_id: str) -> dict[str, Any] | None: ...

    def list_experiments(self, filters: dict[str, Any]) -> list[dict[str, Any]]: ...

    def update_experiment(self, experiment_id: str, updates: dict[str, Any]) -> dict[str, Any]: ...

    def list_running_experiments(self, app_id: str) -> list[dict[str, Any]]: ...

    def create_request_trace(self, trace: dict[str, Any]) -> dict[str, Any]: ...

    def get_request_trace(self, request_id: str) -> dict[str, Any] | None: ...

    def list_request_traces(self, filters: dict[str, Any]) -> list[dict[str, Any]]: ...

    def set_decision(self, experiment_id: str, decision: dict[str, Any]) -> dict[str, Any]: ...

    def get_decision(self, experiment_id: str) -> dict[str, Any] | None: ...

    def append_rollback_log(self, experiment_id: str, rollback_log: dict[str, Any]) -> dict[str, Any]: ...

    def list_rollback_logs(self, experiment_id: str) -> list[dict[str, Any]]: ...

    def append_approval_log(self, experiment_id: str, approval_log: dict[str, Any]) -> dict[str, Any]: ...

    def list_approval_logs(self, experiment_id: str) -> list[dict[str, Any]]: ...

    def reset(self) -> None: ...

